require:
  - rubocop-rake
  - rubocop-rspec

inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

#追加
#
Style/StringConcatenation:
  Enabled: false
#
Naming/AccessorMethodName:
  Enabled: false

